language: node_js

node_js:
   - "0.10.4"

install:
  - npm install node-static mocha-phantomjs

before_script:
  - git clone -b test git://github.com/matchajs/matchajs.org.git _test

script:
  - node _test/server.js http://127.0.0.1:8080/test/runner.html